# -*- coding: utf-8 -*-
import sys

# Form implementation generated from reading ui file '个性化定制.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from read import *
from diji import *
import Gaode_Map_API as MAP

class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName("DockWidget")
        DockWidget.resize(1280, 750)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.listView = QtWidgets.QListView(self.dockWidgetContents)
        self.listView.setGeometry(QtCore.QRect(0, 0, 1280, 862))
        self.listView.setStyleSheet("background-image: url(/Users/yangjinda/Documents/数据结构/数据结构课程设计/课设图片/beautiful3.png);")
        self.listView.setObjectName("listView")
        self.textBrowser = QtWidgets.QTextBrowser(self.dockWidgetContents)
        self.textBrowser.setGeometry(QtCore.QRect(30, 30, 1231, 681))
        self.textBrowser.setStyleSheet("background-color: rgba(255, 255, 255, 76);")
        self.textBrowser.setObjectName("textBrowser")
        self.lcdNumber = QtWidgets.QLCDNumber(self.dockWidgetContents)
        self.lcdNumber.setGeometry(QtCore.QRect(970, 60, 241, 41))
        self.lcdNumber.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.lcdNumber.setObjectName("lcdNumber")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.dockWidgetContents)
        self.textBrowser_2.setGeometry(QtCore.QRect(50, 90, 501, 561))
        self.textBrowser_2.setStyleSheet("background-color: rgba(255, 255, 255, 128);")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.comboBox = QtWidgets.QComboBox(self.dockWidgetContents)
        self.comboBox.setGeometry(QtCore.QRect(270, 370, 104, 26))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_4 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_4.setGeometry(QtCore.QRect(160, 370, 81, 21))
        self.label_4.setStyleSheet("font: 18pt \".AppleSystemUIFont\";")
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton.setGeometry(QtCore.QRect(322, 480, 101, 32))
        self.pushButton.setStyleSheet("font: 18pt \".AppleSystemUIFont\";\n"
"background-color: rgb(88, 253, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_2.setGeometry(QtCore.QRect(50, 50, 91, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_3.setGeometry(QtCore.QRect(690, 110, 91, 91))
        self.label_3.setStyleSheet("background-image: url(/Users/yangjinda/Documents/数据结构/数据结构课程设计/gif/章鱼哥.gif);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_6.setGeometry(QtCore.QRect(580, 110, 91, 91))
        self.label_6.setStyleSheet("background-image: url(/Users/yangjinda/Documents/数据结构/数据结构课程设计/gif/海绵宝宝.gif);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_7.setGeometry(QtCore.QRect(810, 110, 91, 91))
        self.label_7.setStyleSheet("background-image: url(/Users/yangjinda/Documents/数据结构/数据结构课程设计/gif/派大星.gif);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_8.setGeometry(QtCore.QRect(930, 110, 91, 91))
        self.label_8.setStyleSheet("background-image: url(/Users/yangjinda/Documents/数据结构/数据结构课程设计/gif/蟹老板.gif);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.dockWidgetContents)
        self.textBrowser_3.setGeometry(QtCore.QRect(640, 320, 341, 211))
        self.textBrowser_3.setStyleSheet("background-color: rgba(255, 255, 255, 128);")
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.label_9 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_9.setGeometry(QtCore.QRect(640, 250, 101, 51))
        self.label_9.setStyleSheet("font: 24pt \".AppleSystemUIFont\";")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_10.setGeometry(QtCore.QRect(150, 210, 81, 21))
        self.label_10.setStyleSheet("font: 18pt \".AppleSystemUIFont\";")
        self.label_10.setObjectName("label_10")
        self.comboBox_3 = QtWidgets.QComboBox(self.dockWidgetContents)
        self.comboBox_3.setGeometry(QtCore.QRect(260, 210, 221, 26))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.lineEdit_5.setGeometry(QtCore.QRect(220, 130, 211, 31))
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_11 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_11.setGeometry(QtCore.QRect(120, 129, 91, 31))
        self.label_11.setObjectName("label_11")
        self.radioButton = QtWidgets.QRadioButton(self.dockWidgetContents)
        self.radioButton.setGeometry(QtCore.QRect(170, 310, 86, 16))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.dockWidgetContents)
        self.radioButton_2.setGeometry(QtCore.QRect(170, 270, 86, 16))
        self.radioButton_2.setObjectName("radioButton_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.dockWidgetContents)
        self.comboBox_2.setGeometry(QtCore.QRect(270, 170, 81, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_12 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_12.setGeometry(QtCore.QRect(670, 710, 81, 21))
        self.label_12.setStyleSheet("font: 18pt \".AppleSystemUIFont\";")
        self.label_12.setObjectName("label_12")
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        self.label.setGeometry(QtCore.QRect(140, 170, 101, 31))
        self.label.setObjectName("label")
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)

    def retranslateUi(self, DockWidget):
        _translate = QtCore.QCoreApplication.translate
        DockWidget.setWindowTitle(_translate("DockWidget", "DockWidget"))
        self.comboBox.setItemText(0, _translate("DockWidget", "刘公岛"))
        self.comboBox.setItemText(1, _translate("DockWidget", "西霞口神雕山动物园"))
        self.comboBox.setItemText(2, _translate("DockWidget", "西霞口旅游风景区"))
        self.comboBox.setItemText(3, _translate("DockWidget", "火炬八街"))
        self.comboBox.setItemText(4, _translate("DockWidget", "国际海水浴场"))
        self.comboBox.setItemText(5, _translate("DockWidget", "鸡鸣岛"))
        self.comboBox.setItemText(6, _translate("DockWidget", "布鲁威斯号"))
        self.comboBox.setItemText(7, _translate("DockWidget", "华夏城"))
        self.comboBox.setItemText(8, _translate("DockWidget", "威海公园"))
        self.comboBox.setItemText(9, _translate("DockWidget", "幸福门"))
        self.comboBox.setItemText(10, _translate("DockWidget", "悦海公园"))
        self.comboBox.setItemText(11, _translate("DockWidget", "那香海"))
        self.comboBox.setItemText(12, _translate("DockWidget", "成山头"))
        self.label_4.setText(_translate("DockWidget", "必去景点"))
        self.pushButton.setText(_translate("DockWidget", "一键规划"))
        self.pushButton_2.setText(_translate("DockWidget", "🔙"))
        self.textBrowser_3.setHtml(_translate("DockWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.AppleSystemUIFont\'; font-size:18pt;\">具体路径1</span></p></body></html>"))
        self.label_9.setText(_translate("DockWidget", "具体方案"))
        self.label_10.setText(_translate("DockWidget", "交通工具"))
        self.comboBox_3.setItemText(0, _translate("DockWidget", "私家车（不计油费及停车费用）"))
        self.comboBox_3.setItemText(1, _translate("DockWidget", "出租车"))
        self.comboBox_3.setItemText(2, _translate("DockWidget", "电动车"))
        self.label_11.setText(_translate("DockWidget", "输入开始位置"))
        self.radioButton.setText(_translate("DockWidget", "时间最短"))
        self.radioButton_2.setText(_translate("DockWidget", "费用最少"))
        self.comboBox_2.setItemText(0, _translate("DockWidget", "一日游"))
        self.comboBox_2.setItemText(1, _translate("DockWidget", "两日游"))
        self.label_12.setText(_translate("DockWidget", "交通工具"))
        self.label.setText(_translate("DockWidget", "    旅游安排"))
class DockWidget(QtWidgets.QDockWidget, Ui_DockWidget):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.setWindowTitle('威海旅游咨询系统')
        QtCore.QCoreApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling)#设置高分屏适应
        self.radioButton_2.setChecked(True)
        self.pushButton.clicked.connect(self.plan_ge)
    def plan_ge(self):
        text=self.lineEdit_5.text()
        self.textBrowser_3.setText("")
        Matrix_list=MAP.Add_start_Matrix(text)
        day_id=self.comboBox_2.currentIndex()
        transport_id=self.comboBox_3.currentIndex()
        must_id=self.comboBox.currentIndex()
        price_or_time=0 if self.radioButton_2.isChecked() else 1
        cost_str = ''
        if price_or_time == 0:
            cost_str += "总费用(元)为："
        else:
            cost_str += '总时间(h)为：'
        str_road = f"{text}-->"
        if day_id == 0:
            tour, cost, Matrix = one_day_tour(Matrix_list, transport_id, price_or_time, must_id)
            for p in tour:
                if p !=13:
                    str_road = str_road + scenic_dict[p] + "-->"
            cost_str = cost_str + str(cost)
            self.textBrowser_3.setText(str_road + '\n' + cost_str)
        else:
            result = two_day_tour(Matrix_list, transport_id, price_or_time, must_id)
            cost0=cost_str
            for i in range(2):
                str_road =f"第{i+1}天" + '\n'+f"{text}"+"-->"
                road = result[i][0]
                for p in road:
                    if p != 13:
                        str_road = str_road + scenic_dict[p] + "-->"
                str_road+=f"{text}"
                cost_str = cost0 + str(int(result[i][1]))
                self.textBrowser_3.append(str_road+'\n'+cost_str+'\n')





if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    dockWidget = DockWidget()
    dockWidget.show()
    sys.exit(app.exec_())