# -*- coding: utf-8 -*-
import sys

from PyQt5.QtWidgets import QCompleter

from read import read_info,scenic_dict
from fuzzy_query import fuzzy_query
# Form implementation generated from reading ui file '景点查询界面.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

pin2id={'liugondao':0,'xixiakouyeshengdonwuyuan':1,'xixiakoulvyoudujiaqu':2,
         'chengshantou':3,'jimingdao':4,'naxianghai':5,
         'huaxiacheng':6,'guojihaishuiyuchang':7,'huojubajie':8,
         'weihaigonyuan':9,'xingfumeng':10,'yuehaigonyuan':11,'buluweisihao':12}
scenic_inf=read_info()
scenics=list(scenic_dict.values())
class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName("DockWidget")
        DockWidget.resize(1168, 750)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.listWidget = QtWidgets.QListWidget(self.dockWidgetContents)
        self.listWidget.setGeometry(QtCore.QRect(-100, 0, 1291, 741))
        self.listWidget.setObjectName("listWidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.dockWidgetContents)
        self.textBrowser.setGeometry(QtCore.QRect(10, 210, 501, 491))
        self.textBrowser.setStyleSheet("\n"
"background-color: rgb(233, 233, 233);")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.dockWidgetContents)
        self.textBrowser_2.setGeometry(QtCore.QRect(30, 240, 231, 191))
        self.textBrowser_2.setStyleSheet("background-image: url(/Users/yangjinda/Documents/数据结构/数据结构课程设计/数据结构课程设计图片2/华夏城.png);\n"
"")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.line = QtWidgets.QFrame(self.dockWidgetContents)
        self.line.setGeometry(QtCore.QRect(270, 330, 240, 2))
        self.line.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.dockWidgetContents)
        self.textBrowser_3.setGeometry(QtCore.QRect(300, 260, 191, 51))
        self.textBrowser_3.setStyleSheet("font: 24pt \"Lantinghei SC\";\n"
"border-color: rgb(233, 233, 233);\n"
"background-color: rgb(233, 233, 233);")
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        self.label.setGeometry(QtCore.QRect(270, 340, 71, 21))
        self.label.setStyleSheet("font: 14pt \"Lantinghei SC\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_2.setGeometry(QtCore.QRect(340, 370, 221, 16))
        self.label_2.setStyleSheet("font: 14pt \"Lantinghei SC\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_3.setGeometry(QtCore.QRect(310, 390, 201, 21))
        self.label_3.setStyleSheet("font: 13pt \"Lantinghei SC\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_4.setGeometry(QtCore.QRect(330, 410, 121, 16))
        self.label_4.setObjectName("label_4")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.dockWidgetContents)
        self.textBrowser_4.setGeometry(QtCore.QRect(30, 470, 461, 211))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.label_5 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_5.setGeometry(QtCore.QRect(270, 410, 71, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_6.setGeometry(QtCore.QRect(270, 390, 41, 16))
        self.label_6.setStyleSheet("font: 13pt \"Lantinghei SC\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_7.setGeometry(QtCore.QRect(270, 370, 71, 16))
        self.label_7.setStyleSheet("font: 14pt \"Lantinghei SC\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_8.setGeometry(QtCore.QRect(40, 440, 101, 21))
        self.label_8.setStyleSheet("font: 18pt \"Lantinghei SC\";")
        self.label_8.setObjectName("label_8")
        self.pushButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton.setGeometry(QtCore.QRect(30, 100, 91, 32))
        self.pushButton.setStyleSheet("background-color: rgb(255, 197, 184);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_2.setGeometry(QtCore.QRect(160, 100, 91, 32))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 197, 184);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_3.setGeometry(QtCore.QRect(290, 100, 91, 32))
        self.pushButton_3.setStyleSheet("background-color: rgb(255, 197, 184);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_4.setGeometry(QtCore.QRect(420, 100, 91, 32))
        self.pushButton_4.setStyleSheet("background-color: rgb(255, 197, 184);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_5.setGeometry(QtCore.QRect(30, 150, 91, 32))
        self.pushButton_5.setStyleSheet("background-color: rgb(255, 197, 184);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_6.setGeometry(QtCore.QRect(160, 150, 91, 32))
        self.pushButton_6.setStyleSheet("background-color: rgb(255, 197, 184);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_7.setGeometry(QtCore.QRect(290, 150, 91, 32))
        self.pushButton_7.setStyleSheet("background-color: rgb(255, 197, 184);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_8.setGeometry(QtCore.QRect(420, 150, 91, 32))
        self.pushButton_8.setStyleSheet("background-color: rgb(255, 197, 184);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_9 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_9.setGeometry(QtCore.QRect(30, 60, 101, 41))
        self.label_9.setStyleSheet("font: 18pt \"Lantinghei SC\";")
        self.label_9.setObjectName("label_9")
        self.lineEdit = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.lineEdit.setGeometry(QtCore.QRect(340, 30, 491, 41))
        self.lineEdit.setStyleSheet("background-color: rgb(233, 233, 233);\n"
"font: 18pt \"Lantinghei SC\";")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_10 = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_10.setGeometry(QtCore.QRect(840, 30, 71, 51))
        self.pushButton_10.setObjectName("pushButton_10")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.dockWidgetContents)
        self.textBrowser_5.setGeometry(QtCore.QRect(550, 260, 541, 301))
        self.textBrowser_5.setStyleSheet("background-image: url(/Users/yangjinda/Documents/数据结构/数据结构课程设计/材料/地图.png);")
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.guojihaishuiyuchang = QtWidgets.QPushButton(self.dockWidgetContents)
        self.guojihaishuiyuchang.setGeometry(QtCore.QRect(600, 310, 21, 21))
        self.guojihaishuiyuchang.setStyleSheet("background-image: url(//Users/yangjinda/Documents/数据结构/数据结构课程设计/材料/按钮2.png);")
        self.guojihaishuiyuchang.setText("")
        self.guojihaishuiyuchang.setObjectName("guojihaishuiyuchang")
        self.huojubajie = QtWidgets.QPushButton(self.dockWidgetContents)
        self.huojubajie.setGeometry(QtCore.QRect(620, 300, 21, 21))
        self.huojubajie.setStyleSheet("background-image: url(//Users/yangjinda/Documents/数据结构/数据结构课程设计/材料/按钮2.png);")
        self.huojubajie.setText("")
        self.huojubajie.setObjectName("huojubajie")
        self.liugondao = QtWidgets.QPushButton(self.dockWidgetContents)
        self.liugondao.setGeometry(QtCore.QRect(720, 320, 21, 21))
        self.liugondao.setStyleSheet("background-image: url(//Users/yangjinda/Documents/数据结构/数据结构课程设计/材料/按钮2.png);")
        self.liugondao.setText("")
        self.liugondao.setObjectName("liugondao")
        self.xingfumeng = QtWidgets.QPushButton(self.dockWidgetContents)
        self.xingfumeng.setGeometry(QtCore.QRect(670, 320, 21, 21))
        self.xingfumeng.setStyleSheet("background-image: url(//Users/yangjinda/Documents/数据结构/数据结构课程设计/材料/按钮2.png);")
        self.xingfumeng.setText("")
        self.xingfumeng.setObjectName("xingfumeng")
        self.weihaigonyuan = QtWidgets.QPushButton(self.dockWidgetContents)
        self.weihaigonyuan.setGeometry(QtCore.QRect(690, 360, 21, 21))
        self.weihaigonyuan.setStyleSheet("background-image: url(//Users/yangjinda/Documents/数据结构/数据结构课程设计/材料/按钮2.png);")
        self.weihaigonyuan.setText("")
        self.weihaigonyuan.setObjectName("weihaigonyuan")
        self.yuehaigonyuan = QtWidgets.QPushButton(self.dockWidgetContents)
        self.yuehaigonyuan.setGeometry(QtCore.QRect(700, 380, 21, 21))
        self.yuehaigonyuan.setStyleSheet("background-image: url(//Users/yangjinda/Documents/数据结构/数据结构课程设计/材料/按钮2.png);")
        self.yuehaigonyuan.setText("")
        self.yuehaigonyuan.setObjectName("yuehaigonyuan")
        self.huaxiacheng = QtWidgets.QPushButton(self.dockWidgetContents)
        self.huaxiacheng.setGeometry(QtCore.QRect(650, 410, 21, 21))
        self.huaxiacheng.setStyleSheet("background-image: url(//Users/yangjinda/Documents/数据结构/数据结构课程设计/材料/按钮2.png);")
        self.huaxiacheng.setText("")
        self.huaxiacheng.setObjectName("huaxiacheng")
        self.jimingdao = QtWidgets.QPushButton(self.dockWidgetContents)
        self.jimingdao.setGeometry(QtCore.QRect(920, 370, 21, 21))
        self.jimingdao.setStyleSheet("background-image: url(//Users/yangjinda/Documents/数据结构/数据结构课程设计/材料/按钮2.png);")
        self.jimingdao.setText("")
        self.jimingdao.setObjectName("jimingdao")
        self.naxianghai = QtWidgets.QPushButton(self.dockWidgetContents)
        self.naxianghai.setGeometry(QtCore.QRect(870, 410, 21, 21))
        self.naxianghai.setStyleSheet("background-image: url(//Users/yangjinda/Documents/数据结构/数据结构课程设计/材料/按钮2.png);")
        self.naxianghai.setText("")
        self.naxianghai.setObjectName("naxianghai")
        self.buluweisihao = QtWidgets.QPushButton(self.dockWidgetContents)
        self.buluweisihao.setGeometry(QtCore.QRect(970, 420, 21, 21))
        self.buluweisihao.setStyleSheet("background-image: url(//Users/yangjinda/Documents/数据结构/数据结构课程设计/材料/按钮2.png);")
        self.buluweisihao.setText("")
        self.buluweisihao.setObjectName("buluweisihao")
        self.xixiakouyeshengdonwuyuan = QtWidgets.QPushButton(self.dockWidgetContents)
        self.xixiakouyeshengdonwuyuan.setGeometry(QtCore.QRect(1020, 400, 21, 21))
        self.xixiakouyeshengdonwuyuan.setStyleSheet("background-image: url(//Users/yangjinda/Documents/数据结构/数据结构课程设计/材料/按钮2.png);")
        self.xixiakouyeshengdonwuyuan.setText("")
        self.xixiakouyeshengdonwuyuan.setObjectName("xixiakouyeshengdonwuyuan")
        self.xixiakoulvyoudujiaqu = QtWidgets.QPushButton(self.dockWidgetContents)
        self.xixiakoulvyoudujiaqu.setGeometry(QtCore.QRect(1020, 410, 21, 21))
        self.xixiakoulvyoudujiaqu.setStyleSheet("background-image: url(//Users/yangjinda/Documents/数据结构/数据结构课程设计/材料/按钮2.png);")
        self.xixiakoulvyoudujiaqu.setText("")
        self.xixiakoulvyoudujiaqu.setObjectName("xixiakoulvyoudujiaqu")
        self.pushButton_9 = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_9.setGeometry(QtCore.QRect(1070, 420, 21, 21))
        self.pushButton_9.setStyleSheet("background-image: url(//Users/yangjinda/Documents/数据结构/数据结构课程设计/材料/按钮2.png);")
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("chengshantou")
        self.pushButton_11 = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_11.setGeometry(QtCore.QRect(30, 30, 75, 23))
        self.pushButton_11.setObjectName("pushButton_11")
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)

    def retranslateUi(self, DockWidget):
        _translate = QtCore.QCoreApplication.translate
        DockWidget.setWindowTitle(_translate("DockWidget", "DockWidget"))
        self.textBrowser_3.setHtml(_translate("DockWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lantinghei SC\'; font-size:24pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">华夏城</span></p></body></html>"))
        self.label.setText(_translate("DockWidget", "5A级景区"))
        self.label_2.setText(_translate("DockWidget", "全年08:00-17:00开放"))
        self.label_3.setText(_translate("DockWidget", "威海市环翠区华夏路1号"))
        self.label_4.setText(_translate("DockWidget", "(0631)5998999"))
        self.textBrowser_4.setHtml(_translate("DockWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.AppleSystemUIFont\'; font-size:14pt; font-weight:600;\">         威海华夏城景区隶属于华夏文化旅游集团股份有限公司，位于美丽的海滨度假城市威海，是以展示东方古典文化为主的大型生态文化景区。2017年2月25日，山东省威海市威海华夏城景区晋升为国家AAAAA级旅游景区。</span></p></body></html>"))
        self.label_5.setText(_translate("DockWidget", "咨询电话："))
        self.label_6.setText(_translate("DockWidget", "地址："))
        self.label_7.setText(_translate("DockWidget", "开放时间："))
        self.label_8.setText(_translate("DockWidget", "景区简介："))
        self.pushButton.setText(_translate("DockWidget", "天然氧吧"))
        self.pushButton_2.setText(_translate("DockWidget", "动物世界"))
        self.pushButton_3.setText(_translate("DockWidget", "赶海胜地"))
        self.pushButton_4.setText(_translate("DockWidget", "休闲垂钓"))
        self.pushButton_5.setText(_translate("DockWidget", "山美水美"))
        self.pushButton_6.setText(_translate("DockWidget", "公园漫步"))
        self.pushButton_7.setText(_translate("DockWidget", "网红打卡"))
        self.pushButton_8.setText(_translate("DockWidget", "文物古迹"))
        self.label_9.setText(_translate("DockWidget", "快速直达："))
        self.lineEdit.setText(_translate("DockWidget", "输入查询地点"))
        self.pushButton_10.setText(_translate("DockWidget", "🔍"))
        self.pushButton_11.setText(_translate("DockWidget", "返回"))
class DockWidget(QtWidgets.QDockWidget, Ui_DockWidget):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.setWindowTitle('威海旅游咨询系统')
        QtCore.QCoreApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling)#设置高分屏适应

        completer=QCompleter(scenics)
        self.lineEdit.setText("")
        self.lineEdit.setPlaceholderText("请输入要查询的景点名称")
        self.lineEdit.setCompleter(completer)

        self.pushButton_10.clicked.connect(self.onMap)

        self.guojihaishuiyuchang.clicked.connect(self.update_intro)
        self.huojubajie.clicked.connect(self.update_intro)
        self.liugondao.clicked.connect(self.update_intro)
        self.xingfumeng.clicked.connect(self.update_intro)
        self.weihaigonyuan.clicked.connect(self.update_intro)
        self.yuehaigonyuan.clicked.connect(self.update_intro)
        self.huaxiacheng.clicked.connect(self.update_intro)
        self.jimingdao.clicked.connect(self.update_intro)
        self.naxianghai.clicked.connect(self.update_intro)
        self.buluweisihao.clicked.connect(self.update_intro)
        self.xixiakouyeshengdonwuyuan.clicked.connect(self.update_intro)
        self.xixiakoulvyoudujiaqu.clicked.connect(self.update_intro)
        self.pushButton_9.clicked.connect(self.update_intro)

        self.pushButton.pressed.connect(self.remap)
        self.pushButton.clicked.connect(self.label_func1)
        self.pushButton_2.pressed.connect(self.remap)
        self.pushButton_2.clicked.connect(self.label_func2)
        self.pushButton_3.pressed.connect(self.remap)
        self.pushButton_3.clicked.connect(self.label_func3)
        self.pushButton_4.pressed.connect(self.remap)
        self.pushButton_4.clicked.connect(self.label_func4)
        self.pushButton_5.pressed.connect(self.remap)
        self.pushButton_5.clicked.connect(self.label_func5)
        self.pushButton_6.pressed.connect(self.remap)
        self.pushButton_6.clicked.connect(self.label_func6)
        self.pushButton_7.pressed.connect(self.remap)
        self.pushButton_7.clicked.connect(self.label_func7)
        self.pushButton_8.pressed.connect(self.remap)
        self.pushButton_8.clicked.connect(self.label_func8)
        self.remap()
    def update_intro(self):
        btn=self.sender()
        index=pin2id[btn.objectName()]
        self.textBrowser_3.setText(scenic_inf[index]['景点名称'])
        self.label_3.setText(scenic_inf[index]['位置'])
        self.textBrowser_4.setText(scenic_inf[index]['简介'])
    def remap(self):
        self.liugondao.setStyleSheet('QPushButton{background-color: white; border-radius: 5px;}')
        self.xixiakoulvyoudujiaqu.setStyleSheet('QPushButton{background-color: white; border-radius: 5px;}')
        self.xixiakouyeshengdonwuyuan.setStyleSheet('QPushButton{background-color: white; border-radius: 5px;}')
        self.pushButton_9.setStyleSheet('QPushButton{background-color: white; border-radius: 5px;}')
        self.jimingdao.setStyleSheet('QPushButton{background-color: white; border-radius: 5px;}')
        self.naxianghai.setStyleSheet('QPushButton{background-color: white; border-radius: 5px;}')
        self.huaxiacheng.setStyleSheet('QPushButton{background-color: white; border-radius: 5px;}')
        self.guojihaishuiyuchang.setStyleSheet('QPushButton{background-color: white; border-radius: 5px;}')
        self.huojubajie.setStyleSheet('QPushButton{background-color: white; border-radius: 5px;}')
        self.weihaigonyuan.setStyleSheet('QPushButton{background-color: white; border-radius: 5px;}')
        self.xingfumeng.setStyleSheet('QPushButton{background-color: white; border-radius: 5px;}')
        self.yuehaigonyuan.setStyleSheet('QPushButton{background-color: white; border-radius: 5px;}')
        self.buluweisihao.setStyleSheet('QPushButton{background-color: white; border-radius: 5px;}')

    def onMap(self):
        text=self.lineEdit.text()
        self.remap()
        if text=="刘公岛":
            self.liugondao.setStyleSheet('QPushButton{background-color: red; border-radius: 5px;}')
        if text=="西霞口神雕山动物园":
            self.xixiakouyeshengdonwuyuan.setStyleSheet('QPushButton{background-color: red; border-radius: 5px;}')
        if text=='西霞口旅游度假区':
            self.xixiakoulvyoudujiaqu.setStyleSheet('QPushButton{background-color: red; border-radius: 5px;}')
        if text=='成山头':
            self.pushButton_9.setStyleSheet('QPushButton{background-color: red; border-radius: 5px;}')
        if text=='鸡鸣岛':
            self.jimingdao.setStyleSheet('QPushButton{background-color: red; border-radius: 5px;}')
        if text=='那香海国际旅游度假区':
            self.naxianghai.setStyleSheet('QPushButton{background-color: red; border-radius: 5px;}')
        if text=='威海华夏城':
            self.huojubajie.setStyleSheet('QPushButton{background-color: red; border-radius: 5px;}')
        if text=='威海国际海水浴场':
            self.guojihaishuiyuchang.setStyleSheet('QPushButton{background-color: red; border-radius: 5px;}')
        if text=='火炬八街':
            self.huojubajie.setStyleSheet('QPushButton{background-color: red; border-radius: 5px;}')
        if text=='威海公园':
            self.weihaigonyuan.setStyleSheet('QPushButton{background-color: red; border-radius: 5px;}')
        if text=='威海幸福门':
            self.xingfumeng.setStyleSheet('QPushButton{background-color: red; border-radius: 5px;}')
        if text=='悦海公园':
            self.yuehaigonyuan.setStyleSheet('QPushButton{background-color: red; border-radius: 5px;}')
        if text=='布鲁威斯号':
            self.buluweisihao.setStyleSheet('QPushButton{background-color: red; border-radius: 5px;}')




    def label_func1(self):
        self.liugondao.setStyleSheet('QPushButton{background-color: red; border-radius: 5px;}')
        self.pushButton_9.setStyleSheet('QPushButton{background-color: red; border-radius: 5px;}')
    def label_func2(self):
        self.xixiakouyeshengdonwuyuan.setStyleSheet('QPushButton{background-color: red; border-radius: 5px;}')

    def label_func3(self):
        self.naxianghai.setStyleSheet('QPushButton{background-color: red; border-radius: 5px;}')
        self.guojihaishuiyuchang.setStyleSheet('QPushButton{background-color: red; border-radius: 5px;}')
    def label_func4(self):
        self.xixiakoulvyoudujiaqu.setStyleSheet('QPushButton{background-color: red; border-radius: 5px;}')
    def label_func5(self):
        self.liugondao.setStyleSheet('QPushButton{background-color: red; border-radius: 5px;}')
        self.pushButton_9.setStyleSheet('QPushButton{background-color: red; border-radius: 5px;}')
        self.jimingdao.setStyleSheet('QPushButton{background-color: red; border-radius: 5px;}')
    def label_func6(self):
        self.weihaigonyuan.setStyleSheet('QPushButton{background-color: red; border-radius: 5px;}')
        self.yuehaigonyuan.setStyleSheet('QPushButton{background-color: red; border-radius: 5px;}')
    def label_func7(self):
        self.huojubajie.setStyleSheet('QPushButton{background-color: red; border-radius: 5px;}')
        self.xingfumeng.setStyleSheet('QPushButton{background-color: red; border-radius: 5px;}')
    def label_func8(self):
        self.buluweisihao.setStyleSheet('QPushButton{background-color: red; border-radius: 5px;}')





if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    dockWidget = DockWidget()
    dockWidget.show()
    print(scenics)

    sys.exit(app.exec_())