# -*- coding: utf-8 -*-
import sys

# Form implementation generated from reading ui file '详情界面.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName("DockWidget")
        DockWidget.resize(1280, 755)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.listView = QtWidgets.QListView(self.dockWidgetContents)
        self.listView.setGeometry(QtCore.QRect(0, 0, 1280, 862))
        self.listView.setStyleSheet("background-image: url(/Users/yangjinda/Documents/数据结构/数据结构课程设计/课设图片/beautiful2.png);")
        self.listView.setObjectName("listView")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.dockWidgetContents)
        self.textBrowser_2.setGeometry(QtCore.QRect(40, 30, 1201, 681))
        self.textBrowser_2.setStyleSheet("background-color: rgba(255, 255, 255, 76);")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.graphicsView = QtWidgets.QGraphicsView(self.dockWidgetContents)
        self.graphicsView.setGeometry(QtCore.QRect(90, 80, 261, 192))
        self.graphicsView.setStyleSheet("background-image: url(/Users/yangjinda/Documents/数据结构/数据结构课程设计/数据结构课程设计图片2/布鲁威斯号.png);")
        self.graphicsView.setObjectName("graphicsView")
        self.textBrowser = QtWidgets.QTextBrowser(self.dockWidgetContents)
        self.textBrowser.setGeometry(QtCore.QRect(450, 70, 721, 81))
        self.textBrowser.setStyleSheet("background-color: rgba(255, 255, 255, 128);")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.dockWidgetContents)
        self.textBrowser_3.setGeometry(QtCore.QRect(445, 170, 731, 111))
        self.textBrowser_3.setStyleSheet("background-color: rgba(255, 255, 255, 128);")
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        self.label.setGeometry(QtCore.QRect(450, 190, 91, 20))
        self.label.setStyleSheet("font: 18pt \".AppleSystemUIFont\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_2.setGeometry(QtCore.QRect(550, 190, 231, 16))
        self.label_2.setStyleSheet("font: 18pt \".AppleSystemUIFont\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_3.setGeometry(QtCore.QRect(460, 220, 81, 16))
        self.label_3.setStyleSheet("font: 18pt \".AppleSystemUIFont\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_4.setGeometry(QtCore.QRect(550, 220, 611, 16))
        self.label_4.setStyleSheet("font: 18pt \".AppleSystemUIFont\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_5.setGeometry(QtCore.QRect(450, 250, 91, 16))
        self.label_5.setStyleSheet("font: 18pt \".AppleSystemUIFont\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_6.setGeometry(QtCore.QRect(550, 250, 621, 16))
        self.label_6.setStyleSheet("font: 18pt \".AppleSystemUIFont\";")
        self.label_6.setObjectName("label_6")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.dockWidgetContents)
        self.textBrowser_4.setGeometry(QtCore.QRect(85, 321, 1121, 371))
        self.textBrowser_4.setStyleSheet("background-color: rgba(255, 255, 255, 128);")
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.pushButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton.setGeometry(QtCore.QRect(60, 40, 113, 32))
        self.pushButton.setObjectName("pushButton")
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)

    def retranslateUi(self, DockWidget):
        _translate = QtCore.QCoreApplication.translate
        DockWidget.setWindowTitle(_translate("DockWidget", "DockWidget"))
        self.textBrowser.setHtml(_translate("DockWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:48pt;\">布鲁威斯号</span></p></body></html>"))
        self.label.setText(_translate("DockWidget", "开放时间："))
        self.label_2.setText(_translate("DockWidget", "时间1"))
        self.label_3.setText(_translate("DockWidget", "地点："))
        self.label_4.setText(_translate("DockWidget", "地点1"))
        self.label_5.setText(_translate("DockWidget", "门票价格："))
        self.label_6.setText(_translate("DockWidget", "价格1"))
        self.textBrowser_4.setHtml(_translate("DockWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">介绍</span></p></body></html>"))
        self.pushButton.setText(_translate("DockWidget", "🔙"))
class DockWidget(QtWidgets.QDockWidget, Ui_DockWidget):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    dockWidget = DockWidget()
    dockWidget.show()
    sys.exit(app.exec_())